import { SUPABASE_URL, SUPABASE_ANON_KEY } from './supabase-config';
export const SITE_ORIGIN='https://lingobingo-english.k-lobzhanidze.chatgpt.site';
export function appOrigin(req:Request){const url=new URL(req.url);if(url.origin===SITE_ORIGIN||['https://lingobingoenglish.com','https://www.lingobingoenglish.com','http://localhost:3000','http://127.0.0.1:3000'].includes(url.origin))return url.origin;throw Error('Unrecognized application origin');}
export function authCookie(name:string,value:string,origin:string,maxAge:number){return `${name}=${encodeURIComponent(value)}; HttpOnly; SameSite=Lax; Path=/; Max-Age=${maxAge}${origin.startsWith('https:')?'; Secure':''}`;}
export function getCookie(req:Request,name:string){const cookie=(req.headers.get('cookie')||'').split(';').find(part=>part.trim().startsWith(name+'='));if(!cookie)return '';try{return decodeURIComponent(cookie.trim().slice(name.length+1))}catch{return ''}}
function base64url(bytes:Uint8Array){let binary='';for(const b of bytes)binary+=String.fromCharCode(b);return btoa(binary).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');}
export async function createPKCE(){const verifier=base64url(crypto.getRandomValues(new Uint8Array(32)));const challenge=base64url(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(verifier))));return {verifier,challenge};}
export async function authFetch(path:string,body?:unknown){const response=await fetch(SUPABASE_URL+'/auth/v1/'+path,{method:body?'POST':'GET',headers:{apikey:SUPABASE_ANON_KEY,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(15000)});const data=await response.json();if(!response.ok)throw Error('Authentication service rejected the request');return data;}
export function redirect(location:string,cookies:string[]=[]){const headers=new Headers({Location:location,'Cache-Control':'no-store','Referrer-Policy':'no-referrer'});for(const c of cookies)headers.append('Set-Cookie',c);return new Response(null,{status:303,headers});}
export function signInError(origin:string,reason:string){return redirect(origin+'/?auth_error='+encodeURIComponent(reason)+'#Sign%20In',[authCookie('lb_pkce','',origin,0)]);}
